{% set name = "python-pypi-mirror" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-pypi-mirror-{{ version }}.tar.gz
  sha256: 3a7c04f14e67afdf70cdb7050133e6c34c219620352dde53485ef4fe01b0ca91

build:
  entry_points:
    - pypi-mirror=pypi_mirror:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - pypi_mirror
  commands:
    - pip check
    - pypi-mirror --help
  requires:
    - pip

about:
  home: https://github.com/montag451/pypi-mirror
  summary: A script to create a partial PyPI mirror
  description: |
    pypi-mirror is a small script to generate a partial PyPI mirror. It relies
    on pip to do the most difficult part of the job (downloading a package and
    its dependencies).
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/montag451/pypi-mirror
  doc_url: https://github.com/montag451/pypi-mirror#readme


extra:
  recipe-maintainers:
    - ethanwhite
