{% set name = "python-pypi-mirror" %}
{% set version = "5.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python-pypi-mirror-{{ version }}.tar.gz
  sha256: b47d11f17d7dfeb360cb8c161f5720cf6e7a8dea4fa55c3a2e8fbd6d8ba79f18

build:
  entry_points:
    - pypi-mirror=pypi_mirror:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pypi_mirror
  commands:
    - pip check
    - pypi-mirror --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/montag451/pypi-mirror
  summary: A script to create a partial PyPI mirror
  description: |
    pypi-mirror is a small script to generate a partial PyPI mirror. It relies
    on pip to do the most difficult part of the job (downloading a package and
    its dependencies).
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/montag451/pypi-mirror
  doc_url: https://github.com/montag451/pypi-mirror#readme


extra:
  recipe-maintainers:
    - ethanwhite
